package static

import (
	"io/ioutil"

	gen "github.com/dave/jennifer/jen"
)

const ConstFileName = "generated_static_file_const.go"

var staticFiles = [...]string{"sonarqube.go.temp", "client_util.go.temp"}
var staticName = [...]string{"SonarqubeConst", "WebClientConst"}

func GenerateStaticFiles(navDir string, outputPath string) error {
	f := gen.NewFile("generate")
	f.CanonicalPath = "github.com/magicsong/generate-go-for-sonarqube/pkg/generate"
	f.HeaderComment("Code generated by generate-go-for-sonarqub, DON'T mannualy edit it")
	for index, name := range staticFiles {
		content, err := LoadStaticFile(navDir + "/" + name)
		if err != nil {
			return err
		}
		f.Const().Id(staticName[index]).Op("=").Lit(content)
	}
	return f.Save(outputPath + "/" + ConstFileName)
}

func LoadStaticFile(path string) (string, error) {
	bytes, err := ioutil.ReadFile(path)
	if err != nil {
		return "", nil
	}
	return string(bytes), nil
}
